name: mmip-database
services:
  postgres_db:
    image: postgres:latest
    container_name: MMIP_Postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=mmip_db
      - POSTGRES_USER=mmip
      - POSTGRES_PASSWORD=mmip123
    ports:
      - "5432:5432"
    volumes:
      - postgres_db:/var/lib/postgresql/data
volumes:
  postgres_db:
    driver: local
