# This file is used by the GitHub Action to automatically add labels to pull requests

# Add 'repo' label to any root file changes
repo:
  - "*"

# Add 'ci/cd' label to any change in the .github folder
ci/cd:
  - .github/**

# Add 'docs' label to any change in .md files
docs:
  - docs/**

# Add 'test' label to any change in the test folder
test:
  - src/Test/**

# Add 'Server' label to any change to src files within the 'Server' directory
server:
  - src/Server/**

# Add 'client' label to any change to src files within the 'Client' directory
client:
  - src/Client/**
