properties:
  resources:
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: DotNet
      directives:
        description: Install DotNet SDK 7
        allowPrerelease: true
      settings:
        id: Microsoft.DotNet.SDK.7
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: AspNetCore
      directives:
        description: Install AspNetCore 7 runtime
        allowPrerelease: true
      settings:
        id: Microsoft.DotNet.AspNetCore.7
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: Git
      directives:
        description: Install Git
        allowPrerelease: true
      settings:
        id: Git.Git
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Node.js
        allowPrerelease: true
      settings:
        id: OpenJS.NodeJS
        source: winget
  configurationVersion: 0.2.2
