//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ApplicationResource_en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApplicationResource_en() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Client.Resources.ApplicationResource.en", typeof(ApplicationResource_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        internal static string ChallengeComments {
            get {
                return ResourceManager.GetString("ChallengeComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deadline challenge.
        /// </summary>
        internal static string ChallengeDeadline {
            get {
                return ResourceManager.GetString("ChallengeDeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Challenge description.
        /// </summary>
        internal static string ChallengeDescription {
            get {
                return ResourceManager.GetString("ChallengeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Challenge final report.
        /// </summary>
        internal static string ChallengeFinalReport {
            get {
                return ResourceManager.GetString("ChallengeFinalReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no comments posted yet!.
        /// </summary>
        internal static string ChallengeNoComments {
            get {
                return ResourceManager.GetString("ChallengeNoComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phase challenge.
        /// </summary>
        internal static string ChallengePhase {
            get {
                return ResourceManager.GetString("ChallengePhase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load more challenges.
        /// </summary>
        internal static string ChallengesLoadMore {
            get {
                return ResourceManager.GetString("ChallengesLoadMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startdate challenge.
        /// </summary>
        internal static string ChallengeStartDate {
            get {
                return ResourceManager.GetString("ChallengeStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create challenge.
        /// </summary>
        internal static string CreateChallengeTitle {
            get {
                return ResourceManager.GetString("CreateChallengeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write a comment.
        /// </summary>
        internal static string CreateComment {
            get {
                return ResourceManager.GetString("CreateComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post comment.
        /// </summary>
        internal static string CreateCommentButton {
            get {
                return ResourceManager.GetString("CreateCommentButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Challenge deadline.
        /// </summary>
        internal static string FormChallengeDate {
            get {
                return ResourceManager.GetString("FormChallengeDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Challenge description.
        /// </summary>
        internal static string FormChallengeDescription {
            get {
                return ResourceManager.GetString("FormChallengeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Challenge.
        /// </summary>
        internal static string FormChallengeSave {
            get {
                return ResourceManager.GetString("FormChallengeSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short challenge description.
        /// </summary>
        internal static string FormChallengeShortDescription {
            get {
                return ResourceManager.GetString("FormChallengeShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Challenge title.
        /// </summary>
        internal static string FormChallengeTitle {
            get {
                return ResourceManager.GetString("FormChallengeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to upload bannerimage.
        /// </summary>
        internal static string FormChallengeUpload {
            get {
                return ResourceManager.GetString("FormChallengeUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Challenge visibility.
        /// </summary>
        internal static string FormChallengeVisibility {
            get {
                return ResourceManager.GetString("FormChallengeVisibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment type.
        /// </summary>
        internal static string FormCommentType {
            get {
                return ResourceManager.GetString("FormCommentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h1&gt;Privacy Statement and Data Protection Policy&lt;/h1&gt;
        ///
        ///&lt;h2&gt;1. Introduction&lt;/h2&gt;
        ///&lt;p&gt;This Privacy Statement and Data Protection Policy (hereinafter referred to as the &quot;Statement&quot;) describes how MatchMaker Innovation Platform (&quot;we,&quot; &quot;us,&quot; or &quot;our&quot;) collects, uses, discloses, and protects personal data provided by visitors to our website &lt;a href=&quot;https://mm.innovation.io/&quot;&gt;https://mm.innovation.io/&lt;/a&gt; (&quot;the website&quot;).&lt;/p&gt;
        ///
        ///&lt;h2&gt;2. Collected Data&lt;/h2&gt;
        ///&lt;p&gt;We collect personal data voluntarily provided by you [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PrivacyDeclaration {
            get {
                return ResourceManager.GetString("PrivacyDeclaration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something happened on our side, try again later.
        /// </summary>
        internal static string Request_NotFound {
            get {
                return ResourceManager.GetString("Request_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server is unreachable.
        /// </summary>
        internal static string Request_ServiceUnavailable {
            get {
                return ResourceManager.GetString("Request_ServiceUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given data is too big.
        /// </summary>
        internal static string Request_TooLarge {
            get {
                return ResourceManager.GetString("Request_TooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong..
        /// </summary>
        internal static string SnackbarInvalid {
            get {
                return ResourceManager.GetString("SnackbarInvalid", resourceCulture);
            }
        }
    }
}
