//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ApplicationResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApplicationResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Client.Resources.ApplicationResource", typeof(ApplicationResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Challenge aanmaken.
        /// </summary>
        internal static string CreateChallengeTitle {
            get {
                return ResourceManager.GetString("CreateChallengeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Challenge deadline.
        /// </summary>
        internal static string FormChallengeDate {
            get {
                return ResourceManager.GetString("FormChallengeDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Challenge beschrijving.
        /// </summary>
        internal static string FormChallengeDescription {
            get {
                return ResourceManager.GetString("FormChallengeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Challenge aanmaken.
        /// </summary>
        internal static string FormChallengeSave {
            get {
                return ResourceManager.GetString("FormChallengeSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korte challenge beschrijving.
        /// </summary>
        internal static string FormChallengeShortDescription {
            get {
                return ResourceManager.GetString("FormChallengeShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Challenge titel.
        /// </summary>
        internal static string FormChallengeTitle {
            get {
                return ResourceManager.GetString("FormChallengeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klik hier om een bannerafbeelding te uploaden.
        /// </summary>
        internal static string FormChallengeUpload {
            get {
                return ResourceManager.GetString("FormChallengeUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Challenge zichtbaarheid.
        /// </summary>
        internal static string FormChallengeVisibility {
            get {
                return ResourceManager.GetString("FormChallengeVisibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h1&gt;Privacyverklaring en Gegevensbeschermingsbeleid&lt;/h1&gt;
        ///
        ///&lt;h2&gt;1. Inleiding&lt;/h2&gt;
        ///&lt;p&gt;Dit Privacyverklaring en Gegevensbeschermingsbeleid (hierna &quot;Verklaring&quot;) beschrijft hoe MatchMaker Innovation Platform (&quot;wij,&quot; &quot;ons,&quot; of &quot;onze&quot;) persoonlijke gegevens die worden verstrekt door de bezoekers van onze website &lt;a href=&quot;https://mm.innovation.io/&quot;&gt;https://mm.innovation.io/&lt;/a&gt; (&quot;de website&quot;) worden verzamelt, gebruikt, openbaar maakt en beschermt.&lt;/p&gt;
        ///
        ///&lt;h2&gt;2. Verzamelde Gegevens&lt;/h2&gt;
        ///&lt;p&gt;Wij verzamelen persoo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PrivacyDeclaration {
            get {
                return ResourceManager.GetString("PrivacyDeclaration", resourceCulture);
            }
        }
    }
}
