//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMIP.Client.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ApplicationResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApplicationResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MMIP.Client.Resources.ApplicationResource", typeof(ApplicationResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Over MatchMaker.
        /// </summary>
        internal static string AboutMatchMaker {
            get {
                return ResourceManager.GetString("AboutMatchMaker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Het bedrijf MatchMaker maakt zich sterk om innovatie bij het MKB in de regio Noord-Nederland te bevorderen. Het innoveren is geen doel op zich maar moet zorgen voor een vitale regio waarin het MKB meerwaarde kan blijven in de regio bieden via Business-to-Business en Business-to-Consumer..
        /// </summary>
        internal static string AboutMatchMakerDescription {
            get {
                return ResourceManager.GetString("AboutMatchMakerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag Toevoegen.
        /// </summary>
        internal static string Add_Tag {
            get {
                return ResourceManager.GetString("Add_Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ik ga akkoord met de &lt;a href=&quot;/privacyverklaring&quot;&gt;privacyverklaring&lt;/a&gt; van MatchMaker..
        /// </summary>
        internal static string AgreementPrivacyStatement {
            get {
                return ResourceManager.GetString("AgreementPrivacyStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reacties.
        /// </summary>
        internal static string ChallengeComments {
            get {
                return ResourceManager.GetString("ChallengeComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einddatum challenge.
        /// </summary>
        internal static string ChallengeDeadline {
            get {
                return ResourceManager.GetString("ChallengeDeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Challenge beschrijving.
        /// </summary>
        internal static string ChallengeDescription {
            get {
                return ResourceManager.GetString("ChallengeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Challenge eindverslag.
        /// </summary>
        internal static string ChallengeFinalReport {
            get {
                return ResourceManager.GetString("ChallengeFinalReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er zijn nog geen reacties aanwezig!.
        /// </summary>
        internal static string ChallengeNoComments {
            get {
                return ResourceManager.GetString("ChallengeNoComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fase challenge.
        /// </summary>
        internal static string ChallengePhase {
            get {
                return ResourceManager.GetString("ChallengePhase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laad meer challenges.
        /// </summary>
        internal static string ChallengesLoadMore {
            get {
                return ResourceManager.GetString("ChallengesLoadMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Challenges.
        /// </summary>
        internal static string ChallengesPageTitle {
            get {
                return ResourceManager.GetString("ChallengesPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start datum challenge.
        /// </summary>
        internal static string ChallengeStartDate {
            get {
                return ResourceManager.GetString("ChallengeStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Challenge aanmaken.
        /// </summary>
        internal static string CreateChallengeTitle {
            get {
                return ResourceManager.GetString("CreateChallengeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schrijf een reactie.
        /// </summary>
        internal static string CreateComment {
            get {
                return ResourceManager.GetString("CreateComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reactie plaatsen.
        /// </summary>
        internal static string CreateCommentButton {
            get {
                return ResourceManager.GetString("CreateCommentButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mailadres.
        /// </summary>
        internal static string E_mail {
            get {
                return ResourceManager.GetString("E-mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je opgevraagde pagina is hier niet, miauw..
        /// </summary>
        internal static string ErrorDescription {
            get {
                return ResourceManager.GetString("ErrorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Misschien heb je hem opgegeten of is die weggelopen..
        /// </summary>
        internal static string ErrorJoke {
            get {
                return ResourceManager.GetString("ErrorJoke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opgevraagd item:.
        /// </summary>
        internal static string ErrorRequestedItem {
            get {
                return ResourceManager.GetString("ErrorRequestedItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oh oh! Iets is verkeerd gegaan..
        /// </summary>
        internal static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voornaam.
        /// </summary>
        internal static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wachtwoord vergeten?.
        /// </summary>
        internal static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Challenge deadline.
        /// </summary>
        internal static string FormChallengeDate {
            get {
                return ResourceManager.GetString("FormChallengeDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Challenge beschrijving.
        /// </summary>
        internal static string FormChallengeDescription {
            get {
                return ResourceManager.GetString("FormChallengeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Challenge aanmaken.
        /// </summary>
        internal static string FormChallengeSave {
            get {
                return ResourceManager.GetString("FormChallengeSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korte challenge beschrijving.
        /// </summary>
        internal static string FormChallengeShortDescription {
            get {
                return ResourceManager.GetString("FormChallengeShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Challenge titel.
        /// </summary>
        internal static string FormChallengeTitle {
            get {
                return ResourceManager.GetString("FormChallengeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klik hier om een bannerafbeelding te uploaden.
        /// </summary>
        internal static string FormChallengeUpload {
            get {
                return ResourceManager.GetString("FormChallengeUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Challenge zichtbaarheid.
        /// </summary>
        internal static string FormChallengeVisibility {
            get {
                return ResourceManager.GetString("FormChallengeVisibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type reactie.
        /// </summary>
        internal static string FormCommentType {
            get {
                return ResourceManager.GetString("FormCommentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Het doel.
        /// </summary>
        internal static string GoalMatchMaker {
            get {
                return ResourceManager.GetString("GoalMatchMaker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MatchMaker zal zich richten op het actief identificeren van innovatiekansen binnen het MKB in Noord-Nederland en het faciliteren van samenwerkingen tussen ondernemers en experts om duurzame groei te stimuleren. Hiervoor zal dit online platform dienen als basis..
        /// </summary>
        internal static string GoalMatchMakerDescription {
            get {
                return ResourceManager.GetString("GoalMatchMakerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ga terug naar de homepagina.
        /// </summary>
        internal static string GoBackHome {
            get {
                return ResourceManager.GetString("GoBackHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Innovatieplatform.
        /// </summary>
        internal static string Innovationplatform {
            get {
                return ResourceManager.GetString("Innovationplatform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Achternaam.
        /// </summary>
        internal static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bezig met laden....
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inloggen.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onze missie.
        /// </summary>
        internal static string MissionMatchMaker {
            get {
                return ResourceManager.GetString("MissionMatchMaker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wij zorgen dat elke ondernemer met een gerust hart de toekomst tegemoet kan zien!.
        /// </summary>
        internal static string MissionMatchMakerDescription {
            get {
                return ResourceManager.GetString("MissionMatchMakerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nog geen account? Klik hier om je aan te melden..
        /// </summary>
        internal static string NoAccount {
            get {
                return ResourceManager.GetString("NoAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geen tags gevonden, voeg deze toe of zoek op iets anders..
        /// </summary>
        internal static string NoItemsFound {
            get {
                return ResourceManager.GetString("NoItemsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to andere tags.
        /// </summary>
        internal static string OtherTags {
            get {
                return ResourceManager.GetString("OtherTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wachtwoord.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tussenvoegsel.
        /// </summary>
        internal static string Preposition {
            get {
                return ResourceManager.GetString("Preposition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h2&gt;1. Inleiding&lt;/h2&gt;
        ///&lt;p&gt;Dit Privacyverklaring en Gegevensbeschermingsbeleid (hierna &quot;Verklaring&quot;) beschrijft hoe MatchMaker Innovation Platform (&quot;wij,&quot; &quot;ons,&quot; of &quot;onze&quot;) persoonlijke gegevens die worden verstrekt door de bezoekers van onze website &lt;a href=&quot;https://mm.innovation.io/&quot;&gt;https://mm.innovation.io/&lt;/a&gt; (&quot;de website&quot;) worden verzamelt, gebruikt, openbaar maakt en beschermt.&lt;/p&gt;
        ///&lt;br/&gt;
        ///
        ///&lt;h2&gt;2. Verzamelde Gegevens&lt;/h2&gt;
        ///&lt;p&gt;Wij verzamelen persoonlijke gegevens die vrijwillig door jou worden verstr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PrivacyDeclaration {
            get {
                return ResourceManager.GetString("PrivacyDeclaration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacyverklaring en Gegevensbeschermingsbeleid.
        /// </summary>
        internal static string PrivacyPageTitle {
            get {
                return ResourceManager.GetString("PrivacyPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beschrijving.
        /// </summary>
        internal static string ProfileDescription {
            get {
                return ResourceManager.GetString("ProfileDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profielfoto.
        /// </summary>
        internal static string ProfilePicture {
            get {
                return ResourceManager.GetString("ProfilePicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ProfileTitle {
            get {
                return ResourceManager.GetString("ProfileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registreren.
        /// </summary>
        internal static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overige tags.
        /// </summary>
        internal static string RemainingTags {
            get {
                return ResourceManager.GetString("RemainingTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wachtwoord herhalen.
        /// </summary>
        internal static string RepeatPassword {
            get {
                return ResourceManager.GetString("RepeatPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er is iets fout gegaan met het versturen van de data.
        /// </summary>
        internal static string Request_BadRequest {
            get {
                return ResourceManager.GetString("Request_BadRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er is iets fout gegaan aan onze kant, probeer het later nog een keer.
        /// </summary>
        internal static string Request_NotFound {
            get {
                return ResourceManager.GetString("Request_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De server is onbereikbaar.
        /// </summary>
        internal static string Request_ServiceUnavailable {
            get {
                return ResourceManager.GetString("Request_ServiceUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De opgegeven data is te groot.
        /// </summary>
        internal static string Request_TooLarge {
            get {
                return ResourceManager.GetString("Request_TooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onbekende fout.
        /// </summary>
        internal static string Request_Unknown {
            get {
                return ResourceManager.GetString("Request_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoektermen.
        /// </summary>
        internal static string SearchTerms {
            get {
                return ResourceManager.GetString("SearchTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er is iets fout gegaan..
        /// </summary>
        internal static string SnackbarInvalid {
            get {
                return ResourceManager.GetString("SnackbarInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profielfoto uploaden.
        /// </summary>
        internal static string UploadProfilePicture {
            get {
                return ResourceManager.GetString("UploadProfilePicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onze visie.
        /// </summary>
        internal static string VisionMatchMaker {
            get {
                return ResourceManager.GetString("VisionMatchMaker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MatchMaker draagt bij aan een vitaal MKB in Noord-Nederland door te faciliteren in innovatie..
        /// </summary>
        internal static string VisionMatchMakerDescription {
            get {
                return ResourceManager.GetString("VisionMatchMakerDescription", resourceCulture);
            }
        }
    }
}
