//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMIP.Client.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ApplicationResource_en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApplicationResource_en() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MMIP.Client.Resources.ApplicationResource.en", typeof(ApplicationResource_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About MatchMaker.
        /// </summary>
        internal static string AboutMatchMaker {
            get {
                return ResourceManager.GetString("AboutMatchMaker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MatchMaker is committed to promoting innovation among SME&apos;s in the Northern regions of the Netherlands. Innovation is not a goal in itself, but must ensure a vital region in which SME&apos;s can continue to offer added value in the region through Business-to-Business and Business-to-Consumer..
        /// </summary>
        internal static string AboutMatchMakerDescription {
            get {
                return ResourceManager.GetString("AboutMatchMakerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Tag.
        /// </summary>
        internal static string Add_Tag {
            get {
                return ResourceManager.GetString("Add_Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I agree with the &lt;a href=&quot;/privacyverklaring&quot;&gt;privacy statement&lt;/a&gt; of MatchMaker..
        /// </summary>
        internal static string AgreementPrivacyStatement {
            get {
                return ResourceManager.GetString("AgreementPrivacyStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        internal static string ChallengeComments {
            get {
                return ResourceManager.GetString("ChallengeComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deadline challenge.
        /// </summary>
        internal static string ChallengeDeadline {
            get {
                return ResourceManager.GetString("ChallengeDeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Challenge description.
        /// </summary>
        internal static string ChallengeDescription {
            get {
                return ResourceManager.GetString("ChallengeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Challenge final report.
        /// </summary>
        internal static string ChallengeFinalReport {
            get {
                return ResourceManager.GetString("ChallengeFinalReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no comments posted yet!.
        /// </summary>
        internal static string ChallengeNoComments {
            get {
                return ResourceManager.GetString("ChallengeNoComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phase challenge.
        /// </summary>
        internal static string ChallengePhase {
            get {
                return ResourceManager.GetString("ChallengePhase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load more challenges.
        /// </summary>
        internal static string ChallengesLoadMore {
            get {
                return ResourceManager.GetString("ChallengesLoadMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Challenges.
        /// </summary>
        internal static string ChallengesPageTitle {
            get {
                return ResourceManager.GetString("ChallengesPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startdate challenge.
        /// </summary>
        internal static string ChallengeStartDate {
            get {
                return ResourceManager.GetString("ChallengeStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create challenge.
        /// </summary>
        internal static string CreateChallengeTitle {
            get {
                return ResourceManager.GetString("CreateChallengeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write a comment.
        /// </summary>
        internal static string CreateComment {
            get {
                return ResourceManager.GetString("CreateComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post comment.
        /// </summary>
        internal static string CreateCommentButton {
            get {
                return ResourceManager.GetString("CreateCommentButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail address.
        /// </summary>
        internal static string E_mail {
            get {
                return ResourceManager.GetString("E-mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your requested page is not here, meow..
        /// </summary>
        internal static string ErrorDescription {
            get {
                return ResourceManager.GetString("ErrorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maybe you ate it or it ran away..
        /// </summary>
        internal static string ErrorJoke {
            get {
                return ResourceManager.GetString("ErrorJoke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested item:.
        /// </summary>
        internal static string ErrorRequestedItem {
            get {
                return ResourceManager.GetString("ErrorRequestedItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uh-oh! Something went wrong..
        /// </summary>
        internal static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        internal static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password?.
        /// </summary>
        internal static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Challenge deadline.
        /// </summary>
        internal static string FormChallengeDate {
            get {
                return ResourceManager.GetString("FormChallengeDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Challenge description.
        /// </summary>
        internal static string FormChallengeDescription {
            get {
                return ResourceManager.GetString("FormChallengeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Challenge.
        /// </summary>
        internal static string FormChallengeSave {
            get {
                return ResourceManager.GetString("FormChallengeSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short challenge description.
        /// </summary>
        internal static string FormChallengeShortDescription {
            get {
                return ResourceManager.GetString("FormChallengeShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Challenge title.
        /// </summary>
        internal static string FormChallengeTitle {
            get {
                return ResourceManager.GetString("FormChallengeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to upload bannerimage.
        /// </summary>
        internal static string FormChallengeUpload {
            get {
                return ResourceManager.GetString("FormChallengeUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Challenge visibility.
        /// </summary>
        internal static string FormChallengeVisibility {
            get {
                return ResourceManager.GetString("FormChallengeVisibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment type.
        /// </summary>
        internal static string FormCommentType {
            get {
                return ResourceManager.GetString("FormCommentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our goal.
        /// </summary>
        internal static string GoalMatchMaker {
            get {
                return ResourceManager.GetString("GoalMatchMaker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MatchMaker will focus on actively identifying innovation opportunities within the SME&apos;s in the Northern Netherlands and facilitating collaborations between entrepreneurs and experts to stimulate sustainable growth. For this, this online platform will serve as a basis..
        /// </summary>
        internal static string GoalMatchMakerDescription {
            get {
                return ResourceManager.GetString("GoalMatchMakerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go back home.
        /// </summary>
        internal static string GoBackHome {
            get {
                return ResourceManager.GetString("GoBackHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Innovationplatform.
        /// </summary>
        internal static string Innovationplatform {
            get {
                return ResourceManager.GetString("Innovationplatform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        internal static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our mission.
        /// </summary>
        internal static string MissionMatchMaker {
            get {
                return ResourceManager.GetString("MissionMatchMaker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We ensure that every entrepreneur can face the future with peace of mind.
        /// </summary>
        internal static string MissionMatchMakerDescription {
            get {
                return ResourceManager.GetString("MissionMatchMakerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No account yet? Click here to sign up..
        /// </summary>
        internal static string NoAccount {
            get {
                return ResourceManager.GetString("NoAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No tags found, add this one or change your search term..
        /// </summary>
        internal static string NoItemsFound {
            get {
                return ResourceManager.GetString("NoItemsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to other tags.
        /// </summary>
        internal static string OtherTags {
            get {
                return ResourceManager.GetString("OtherTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preposition.
        /// </summary>
        internal static string Preposition {
            get {
                return ResourceManager.GetString("Preposition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///&lt;h2&gt;1. Introduction&lt;/h2&gt;
        ///&lt;p&gt;This Privacy Statement and Data Protection Policy (hereinafter referred to as the &quot;Statement&quot;) describes how MatchMaker Innovation Platform (&quot;we,&quot; &quot;us,&quot; or &quot;our&quot;) collects, uses, discloses, and protects personal data provided by visitors to our website &lt;a href=&quot;https://mm.innovation.io/&quot;&gt;https://mm.innovation.io/&lt;/a&gt; (&quot;the website&quot;).&lt;/p&gt; 
        ///&lt;br/&gt;
        ///
        ///&lt;h2&gt;2. Collected Data&lt;/h2&gt;
        ///&lt;p&gt;We collect personal data voluntarily provided by you when filling out forms on our website, such  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PrivacyDeclaration {
            get {
                return ResourceManager.GetString("PrivacyDeclaration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Statement and Data Protection Policy.
        /// </summary>
        internal static string PrivacyPageTitle {
            get {
                return ResourceManager.GetString("PrivacyPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string ProfileDescription {
            get {
                return ResourceManager.GetString("ProfileDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile photo.
        /// </summary>
        internal static string ProfilePicture {
            get {
                return ResourceManager.GetString("ProfilePicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string ProfileTitle {
            get {
                return ResourceManager.GetString("ProfileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining tags.
        /// </summary>
        internal static string RemainingTags {
            get {
                return ResourceManager.GetString("RemainingTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat password.
        /// </summary>
        internal static string RepeatPassword {
            get {
                return ResourceManager.GetString("RepeatPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong with sending of the data.
        /// </summary>
        internal static string Request_BadRequest {
            get {
                return ResourceManager.GetString("Request_BadRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something happened on our side, try again later.
        /// </summary>
        internal static string Request_NotFound {
            get {
                return ResourceManager.GetString("Request_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server is unreachable.
        /// </summary>
        internal static string Request_ServiceUnavailable {
            get {
                return ResourceManager.GetString("Request_ServiceUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given data is too big.
        /// </summary>
        internal static string Request_TooLarge {
            get {
                return ResourceManager.GetString("Request_TooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error.
        /// </summary>
        internal static string Request_Unknown {
            get {
                return ResourceManager.GetString("Request_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search terms.
        /// </summary>
        internal static string SearchTerms {
            get {
                return ResourceManager.GetString("SearchTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong..
        /// </summary>
        internal static string SnackbarInvalid {
            get {
                return ResourceManager.GetString("SnackbarInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload profile picture.
        /// </summary>
        internal static string UploadProfilePicture {
            get {
                return ResourceManager.GetString("UploadProfilePicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our vision.
        /// </summary>
        internal static string VisionMatchMaker {
            get {
                return ResourceManager.GetString("VisionMatchMaker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MatchMaker contributes to a vital SME sector in Northern Netherlands by facilitating innovation..
        /// </summary>
        internal static string VisionMatchMakerDescription {
            get {
                return ResourceManager.GetString("VisionMatchMakerDescription", resourceCulture);
            }
        }
    }
}
