name: Pull Request Labeling
on:
  - pull_request_target

jobs:
  label-pr:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Label pull request
        uses: actions/labeler@v4
        with:
          dot: true